### ISSUE TITLE
make recipies use ntm recources

### ISSUE THREAD

**Issue by Shotgn995533** [RagexPrince683/mchelio#56]
Vehicles are seriously way to cheap and custom recipies are hard to make cause there are so many.
Ntm is a dependency so why not use steel, aluminum, titanium, etc. and also use the assembly machine if possible because it can take way more inputs. it would also be nice if newer vehicles would take more advanced materials like cmb steel or tc alloy so the vehicles get better with ntm progression.

**Comment by Shotgn995533** [comment]
i would also contribute recipies

**Comment by RagexPrince683** [comment]
I'm not doing this, and I'm trying to get away from NTM with my own fork of it because it is not realistic enough. I will update recipes at some point. Feel free to do it yourself.
